apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: web-service
  labels:
    component: mysql
spec:
  selector:
    matchLabels:
      component: mysql
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        component: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.36
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: web@123
            # - name: MYSQL_DB
            #   value: mysql
            # - name: MYSQL_USER
            #   value: mysql
            # - name: MYSQL_PASSWORD
            #   value: mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: linode-block-storage-retain
        resources:
          requests:
            storage: 5Gi
